From crossbario/crossbar

run for eachArg in sys.argv:   
run print(eachArg)


RUN apt-get update && apt-get -y upgrade  && apt-get install -y python3-pip python3
run  IP= int(sys.argv[1])
run -d -p IP:8080 --name="crossbar-router" crossbario/crossbar 
